// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnBvOUgDEZ3nwmPYsSarYgd6mXPqQuOB0',
    appId: '1:954766812094:web:8122c7d5fef31757f9cfef',
    messagingSenderId: '954766812094',
    projectId: 'chat-app-1e31b',
    authDomain: 'chat-app-1e31b.firebaseapp.com',
    storageBucket: 'chat-app-1e31b.appspot.com',
    measurementId: 'G-0YS25S5LLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyK1ojN7tPcbgH5f3jwRV72vHn0S0InZE',
    appId: '1:954766812094:android:b83df70d3ee288f1f9cfef',
    messagingSenderId: '954766812094',
    projectId: 'chat-app-1e31b',
    storageBucket: 'chat-app-1e31b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyL6f2zBn3UQI3aGOaFpi6BLZNE7nwEM',
    appId: '1:954766812094:ios:f5ccc5e8779d4864f9cfef',
    messagingSenderId: '954766812094',
    projectId: 'chat-app-1e31b',
    storageBucket: 'chat-app-1e31b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIyL6f2zBn3UQI3aGOaFpi6BLZNE7nwEM',
    appId: '1:954766812094:ios:bed14b86c6c2d1def9cfef',
    messagingSenderId: '954766812094',
    projectId: 'chat-app-1e31b',
    storageBucket: 'chat-app-1e31b.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
